In [2]:
# random number- random means spmething that can not be predicted logically
import numpy as np
from numpy import random

In [11]:
# i need to print any number randomly from 0 to 100
# random having lot of functionaliteis(rand,randint,choice...)
random_number = random.randint(100)
print(random_number)

91


In [18]:
# i need to print any number randomly from 0 to 5
# random having lot of functionaliteis(rand,randint,choice...)
random_number = random.randint(5)
print(random_number)

1


In [24]:
# rand function returns float values in between 0 to 1
rand_number = random.rand()
print(rand_number)

0.5383582709995218


In [25]:
# genrated 1-D array containg range mentioning in size method and range is 0 to 100
result = random.randint(100,size=(10))
print(result)

[83 99 56 81 43 21 95 99 70 19]


In [26]:
# genrated 1-D array containg range mentioning in size method and range is 0 to 100
result = random.randint(10,size=(5))
print(result)

[1 6 6 4 6]


In [27]:
# genrated 2-D array containg range mentioning in size method and range is 0 to 100
result = random.randint(100,size=(2,5))
print(result)

[[99 22 56 12  0]
 [ 5 92 19 97 94]]


In [29]:
# genrated 2-D array containg range mentioning in size method and range is 0 to 100
result = random.randint(100,size=(5,3))
print(result)

[[64 99 62]
 [13 16 49]
 [75 97 22]
 [25  6 18]
 [45 32 79]]


In [30]:
# genrated 2-D array containg range mentioning in size method and range is 0 to 5
result = random.randint(5,size=(5,3))
print(result)

[[4 0 4]
 [3 2 3]
 [1 0 0]
 [4 2 4]
 [4 1 2]]


In [31]:
# genrated 3-D array containg range mentioning in size method and range is 0 to 5
result = random.randint(10,size=(2,5,3)) # 2*5*3
# first 2 is 2-D arrays are 2
# in each 2D having again 1-D arrays are 5
# 3 is each 1-D having 3 elements
print(result)

[[[2 7 8]
  [1 6 2]
  [6 0 3]
  [3 6 1]
  [5 5 8]]

 [[0 6 6]
  [5 2 9]
  [5 4 6]
  [0 3 0]
  [1 3 1]]]


In [36]:
# in random number picking we have one option for select perticular elements from the array using choice
# choice - functionality used to pick number from list
choice_number = random.choice([2,4,6,8])
print(choice_number)

8


In [37]:
# Create 2-D array using choice method
result = random.choice([2,4,6,8,10],size = (3,3))
print(result)

[[10  8  6]
 [ 6  6 10]
 [ 6  2  2]]


In [38]:
output = random.rand(3,5)
print(output)

[[0.01798023 0.15682416 0.28954705 0.5508272  0.5372175 ]
 [0.18317907 0.91056994 0.24281487 0.29972547 0.1686627 ]
 [0.61761999 0.1646796  0.90845634 0.23398262 0.09769778]]


In [39]:
# Numpy sorting arrays
array1 = np.array([5,6,3,2,7,1,9])
# sort is function in numpy
print(np.sort(array1))

[1 2 3 5 6 7 9]


In [40]:
array2 = np.array([[3,4,2,1],[8,5,7,6]])
print(np.sort(array2))

[[1 2 3 4]
 [5 6 7 8]]


In [41]:
array3 = np.array(['venkat','bhavya','aniket','sonam','tanjeela','indu','joseph'])
print(np.sort(array3))

['aniket' 'bhavya' 'indu' 'joseph' 'sonam' 'tanjeela' 'venkat']


In [42]:
array4 = np.array([True,False,True,False,False])
print(np.sort(array4))

[False False False  True  True]


In [43]:
ages = np.array([29,30,25,31,35,40,43])
condition = ages>30
result = ages[condition]
print(condition)
print(result)

[False False False  True  True  True  True]
[31 35 40 43]


In [44]:
# getting even number ages from the array
ages = np.array([29,30,25,31,35,40,43])
condition = ages%2==0
result = ages[condition]
print(condition)
print(result)

[False  True False False False  True False]
[30 40]
