In [1]:
# Numpy slicing
# slicing - [start:end]- start is inclusive end is exclusive

import numpy as np
array1 = np.array([2,4,6,8,10,12,14,16])
print(array1)

[ 2  4  6  8 10 12 14 16]


In [3]:
print(array1[2:5]) # indexes 2,3,4

[ 6  8 10]


In [4]:
print(array1[5:8])

[12 14 16]


In [5]:
print(array1[5:]) # here end index position not mention the it's return all the elements from start index


[12 14 16]


In [6]:
# accessing elements from 2-D array
array2 = np.array([[2,4,6,8,10,12],[1,3,5,7,9,11]])
print(array2)

[[ 2  4  6  8 10 12]
 [ 1  3  5  7  9 11]]


In [8]:
print(array2[1])

[ 1  3  5  7  9 11]


In [9]:
print(array2[0])

[ 2  4  6  8 10 12]


In [11]:
print(array2[0,4:6])

[10 12]


In [12]:
print(array2[1,1:4])

[3 5 7]


In [13]:
array3 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,13]]])
print(array3)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 13]]]


In [16]:
print(array3[0,0,1:])

[2 3]


In [19]:
print(array3[1,1,1:])

[11 13]


In [20]:
# dtype -  we can findout the array is which data type formate
array4 = np.array([1,2,3,4,5])
array5 = np.array([1.5,2.5,3.5,4.5,5.5])
array6 = np.array(['benz','suzuki','audi','bmw','tata'])
print(array4)
print(array5)
print(array6)

[1 2 3 4 5]
[1.5 2.5 3.5 4.5 5.5]
['benz' 'suzuki' 'audi' 'bmw' 'tata']


In [21]:
print(array4.dtype)
print(array5.dtype)
print(array6.dtype)

int32
float64
<U6


In [22]:
# define all the elements in array in perticular data type
array7 = np.array([1,2,3,4],dtype='float64')
print(array7)

[1. 2. 3. 4.]


In [24]:
# define all the elements in array in perticular data type
array7 = np.array([1,2,3,4],dtype='f')
print(array7)

[1. 2. 3. 4.]


In [23]:
# define all the elements in array in perticular data type
array7 = np.array([1,2,3,4],dtype='S')
print(array7)

[b'1' b'2' b'3' b'4']


In [25]:
# define all the elements in array in perticular data type
array7 = np.array([1,2,3,4],dtype='U')
print(array7)

['1' '2' '3' '4']


In [26]:
# define all the elements in array in perticular data type
array8 = np.array([1.0,2.0,3.0,4.0],dtype='int32')
print(array8)

[1 2 3 4]


In [31]:
# Numpy array Shape - shape of an array is the number of elements in each dimension
# findout the shape we are using shape function in numpy

array10 = np.array([1,2,3,4,5])
array11 = np.array([[2,4,6,8],[1,3,5,7]])
array12 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print('1-D array \n',array10)
print('2-D array \n',array11)
print('3-D array \n',array12)

1-D array 
 [1 2 3 4 5]
2-D array 
 [[2 4 6 8]
 [1 3 5 7]]
3-D array 
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [33]:
print(array10.shape)
print(array11.shape)
print(array12.shape)

(5,)
(2, 4)
(2, 2, 3)


In [34]:
array12 = np.array([2,4,6,8,10],ndmin=4)
print(array12)
print(array12.shape)

[[[[ 2  4  6  8 10]]]]
(1, 1, 1, 5)


In [35]:
array13 = np.array([1,2,3,4,5,6,7,8,9,10],ndmin=6)
print(array13)
print(array13.shape)

[[[[[[ 1  2  3  4  5  6  7  8  9 10]]]]]]
(1, 1, 1, 1, 1, 10)
